### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by samth** [racket/racket-ci#2]
Copied from Slack, should be separated out.

- [x] build minimal racket distributions from GHA on every commit and upload them somewhere
- [x] create a GHA for testing DrRacket
- [x] figure out how to run racket/racket actions for CS on every push to racket/ChezScheme
- [x] add some CI for racket/ChezScheme (edited) 
- [ ] create a way to go from the information in a DrDr run (primarily the commit here: http://drdr.racket-lang.org/53462/ and the pkg info here: http://drdr.racket-lang.org/53462/pkg-show) to a build of all of racket
- [ ] slack notifications for GHA results

**Comment by pmatos** [comment]
@samth Given https://github.com/racket/drracket/blob/master/.github/workflows/ci.yml is the second checkbox ticked?
Also, for the last checkbox, we have https://www.freecodecamp.org/news/what-are-github-actions-and-how-can-you-automate-tests-and-slack-notifications/ and https://awesomeopensource.com/project/rtCamp/action-slack-notify?categoryPage=3

**Comment by samth** [comment]
Yes, I checked that box. And those look good.
